### ISSUE TITLE
Unable to read dimensions from certain SVG files

### ISSUE THREAD

**Issue by lehni** [SidOfc/leather#21]
I found a bunch of more SVG files where the size is read wrongly. It results in `{ width: 0, height: 0 }` in these:

[wrong-dimensions-1.svg](https://github.com/SidOfc/leather/assets/213275/f331ca23-935c-49e2-8a7a-466beb804121)
[wrong-dimensions-2.svg](https://github.com/SidOfc/leather/assets/213275/2be28ad8-5d40-4db1-9b9b-057d577efecb)

**Comment by lehni** [comment]
I will take a look at this bug now.

**Comment by lehni** [comment]
Ok so the main "problem" here is that that there's no XML processing instruction in this file (`<?xml version="1.0" encoding="UTF-8"?>`) and the SVG tag starts at 0. So this check here fails:

```js
    if (found.start && found.end) {
```

But with `!== null` checks we're getting the wrong dimensions again, namely those from the rect inside, just like in #18.

```js
    if (found.start !== null && found.end !== null) {
```

**Comment by lehni** [comment]
So it turns out the SVG tag is so short here that start and end are in the same "overlapping" chunk, and only start is taken from it. I don't understand why the chunks we're looking at need to be overlapping? It looks like this results in looking at the same data multiple times…

@SidOfc can you explain why it's done this way?

**Comment by lehni** [comment]
So #23 fixes this, but I think the overlapping part of the code isn't needed at all here. We can now just loop through neighbouring chunks without the need for them overlapping. I'm reluctant to change this though because I don't understand why it was done this way in the first place.

**Comment by SidOfc** [comment]
@lehni the overlapping part is present in order section out the file into chunks of specific sizes. The reason why there's an overlap here is because an SVG file with lots of junk at the top could have for example a chunk ending in `<sv` and the next only containing the `g`.

Because of this being unpredictable, the "current" and "last" chunks are stitched together to form a single overlapping region which ensures that the tag name will always be present in its entirety at least once.

Given this information, do you have any ideas on how to improve this? I don't mind getting rid of this method of processing SVG images as long as it doesn't come with too much performance overhead. A non-streaming XML parser for example would parse the entire file in one go.

**Comment by lehni** [comment]
Thanks for the explanation, that makes sense. I guess the alternative would be using a streaming XML parser, indeed. I'm totally fine with the status quo though! Feel free to close this issue, since the bug is fixed. Oh, and thanks for the release @SidOfc !

**Comment by SidOfc** [comment]
No problem, happy to elaborate :) I'm not too fond of this overlapping solution myself but aside from using a streaming XML parser I did not see another way. The reason I decided not to use a streaming XML parser was to keep leather dependency free basically.

cheers for the reports, if you do find a more elegant way to handle SVG which will be less prone to edge-case errors I'd be interested in hearing it as well 👍
