### ISSUE TITLE
Unable to read dimensions from certain MP4 files

### ISSUE THREAD

**Issue by lehni** [SidOfc/leather#22]
I found some MP4 files where the size is read wrongly. It results in `{ width: 0, height: 0 }` in these:

[wrong-dimensions-1.mp4](https://github.com/SidOfc/leather/assets/213275/78f97eb2-abc4-40ec-b573-5724c3369a5f)

**Comment by SidOfc** [comment]
In this case the "magic bytes" were not recognized by leather. I patched mp4 magic byte regex to allow matching the bytes in above video (should be similar for other mp42 videos). Closing this however if other files cannot be detected (usually when `mime` is `undefined`) please do feel free to reopen.

Cheers again!

Oh, one more note, I added the videos in this issue and #24 to my test suite. Is it OK for me to use these for that purpose though? Otherwise I'll remove them of course.

**Comment by lehni** [comment]
@SidOfc great thank you! And yes feel free to use the files :)

**Comment by SidOfc** [comment]
That's wonderful, thank you very much! Should this become a problem later on feel free to hit me up for removal 👌
