### ISSUE TITLE
Retrieving data about animated png/webp

### ISSUE THREAD

**Issue by profispojka** [SidOfc/leather#5]
This project seems awesome.

Does it also work in browser?

It would be awesome, if we could retrieve data such as number of frames in animated png or webp, is something like that planned?

Thank you.

**Comment by SidOfc** [comment]
Hello @profispojka,

Currently only Node is supported since it relies on streams and file system access. That said the requested feature could be implemented to work on Node but I'm not sure how much work it would be and if I'd be willing to put that work in at the moment.

I think I'll leave this open for now and check this out somewhere in the future. Would you mind elaborating on your use case? I'm quite curious as to what kind of ideas would require this functionality :)

**Comment by profispojka** [comment]
Hi sid. I am making a simple game engine tha relies on image animation length - after end of the animation an event is triggered. Currently it uses png animations, but I would like to use a format that does use less space.

**Comment by SidOfc** [comment]
Hi prof, cheers for the context. While I _could_ build some frame counting in the png extractor, doing so could make others wonder why I wouldn't do this for other video formats as well.

I am not an expert in file formats in general and do not intend to learn how to count frames in all video formats so I can provide this feature "consistently" if that makes sense. (I tried extracting video duration for all formats once, it wasn't fun).

My reasoning for _not_ implementing this feature is as follows:
- Seems like you require browser support - I'm not willing to rewrite Leather "just" for this edge-case purpose.
- Will take a ton of time for me to read the specs to figure out how to extract animation frames from _every_ supported video format.

All that said I do wish you the best with your game engine, I hope you'll find some tool which does what you need it to do.

I'll be closing this, cheers for the request and the reply!
