### ISSUE TITLE
Support reading from buffers instead of files

### ISSUE THREAD

**Issue by lehni** [SidOfc/leather#6]
This library is great and exactly what I am looking for, but sadly it assumes the data is in a file, which isn't the case in my scenario. A big advantage of `image-size` is that it supports buffers, but sadly doesn't handle videos. Why can't we have both? :)

**Comment by SidOfc** [comment]
Glad you're liking it :)

I see where you're coming from. I think I can add support for buffers as well, after all most of the actual reading and parsing is done on a buffer after reading bytes so it should be possible to accept a buffer instead and read from that.

I'll try to look into supporting this somewhere before next Monday since I'm a bit busy this week.

Good idea, cheers for suggesting 👍

**Comment by lehni** [comment]
That's great to hear! Thanks for the swift reply!

This would be to run size detection on partially loaded files, e.g. buffers created from a stream during uploads. So ideally, it would attempt to read the size, and return `null` if nothing can be read (just like `image-size` does), or an object with the determined dimensions and mime type if it was successful. It would not make sense to include the `size` property, since it would not be the actual final size.

**Comment by lehni** [comment]
BTW, while looking at the code, I noticed that this line here can be removed entirely:

https://github.com/SidOfc/leather/blob/d8deb66ca8ffd81395823db6e26b2999bc9c0c9f/src/util.js#L42

**Comment by lehni** [comment]
Here's the part of the code where I'd like to switch from `image-size` to `leather`, to support video dimensions:

https://github.com/ditojs/dito/blob/66314a6131d4aab309980a1cb8b22feb9b645ebe/packages/server/src/storage/Storage.js#L205-L211

**Comment by SidOfc** [comment]
I see @lehni, thanks for pointing out that `const ext` 👍 Will remove that as well once I start working on this.

**Comment by SidOfc** [comment]
Hello @lehni, I've just released version 2.1.0 (https://www.npmjs.com/package/leather) which supports reading from buffers in addition to file paths. You should now be able to go ahead and pass them to any `attributes` method :)

Closing since I tested this locally, but if you still find issues with the feature please add a comment below. Thanks again and enjoy :)

**Comment by SidOfc** [comment]
Hmn seems like I did miss a comment about some specifics regarding returning `null` though. This may be something I can add in a version 2.1.1 though. At any rate for now a check can be done before calling `attributes` to see if the buffer actually contains anything as a workaround. Additionally, leather does return a `size` attribute which you can check to see if whatever you passed in has any actual content.

When `attributes(target).size === 0` it means that no extractor was used (since extractors are keyed by magic bytes which determine extractor to use) and thus can be assumed to be an invalid/unknown result.

This might actually be nicer than returning `null` since while `null` clearly indicates "no result" it's a bit of a weird value to work with in JS (`typeof null === 'object' // => true`).

**Comment by lehni** [comment]
Oh wow, that was fast! Super good. I've just given it a spin now, and it seems to work really well for images. But I did find some problems with two video files I used for testing. I'll create a separate issue for this.
