### ISSUE TITLE
Problem reading dimensions of MP4 files

### ISSUE THREAD

**Issue by lehni** [SidOfc/leather#9]
I tested with these two files, and both cause issues currently:

https://kdrive.infomaniak.com/app/share/505458/af1779c8-11db-4bcf-8e39-55d791d8401d
https://kdrive.infomaniak.com/app/share/505458/3f1cdb78-b7b7-44b4-83a1-a094c022be52

The first one is identified as mp4, but doesn't find the width and height:
`{ width: 0, height: 0, size: 19282849, mime: 'video/mp4' }`

The second one isn't event found to be an mp4:
`{ width: 0, height: 0, size: 0, mime: undefined }`

**Comment by lehni** [comment]
I noticed that the second file has the audio track before the video track. The detection seems to look for the first track and take it from there, so that may explain why this would fail?

**Comment by SidOfc** [comment]
Hmn interesting indeed! There are a few tests but the files are small and admittedly quite simple to allow tests to run fast. A quick check with `file` yields the following:

<img width="791" alt="image" src="https://user-images.githubusercontent.com/3225058/226148667-4890e641-1074-47fc-93ee-2834c1f70473.png">

Here we can see that the test files currently in use are either itunes or mp4 v1 whereas the videos you're using are mp4 v2. Will look into this when I have some more time. Likely somewhere next week.

Cheers for the report 👍

**Comment by SidOfc** [comment]
Hi again @lehni, I decided to look into it a bit sooner and have merged a patch. It's not quite perfect though as one of the example files is really slow to process:

<img width="680" alt="image" src="https://user-images.githubusercontent.com/3225058/226183464-db1c050a-06c0-40c9-9a4c-cfe7786c7db6.png">

With this order:
```javascript
console.log(attributes('/tmp/heat.mp4'));
console.log(attributes('/tmp/shoes.mp4'));
console.log(attributes('test/files/example.mp4'));
console.log(attributes('test/files/example.m4v'));
```

This `heat.mp4` file seems to be structured quite a bit different which causes the parser I [ported from java](https://github.com/sannies/mp4parser/blob/master/examples/src/main/java/com/google/code/mp4parser/example/GetHeight.java) to fail in which case I fall back to my original method which takes quite long since metadata is placed at the end of the file and is being read 4 bytes at a time since it attempts to find `tkhd` header by reading 4 bytes and comparing them.

I'm going to do some additional research at some point to see if I can figure out why. For now, it works and the `shoes.mp4` file parses quite fast at least.

**Comment by SidOfc** [comment]
I've just released another patch version which allows `heat.mp4` to be processed as fast as the other mp4 files. I'm not entirely sure why but one thing which stood out was that the `ftyp` header had a size of `28` instead of `32` which all other mp4 files have. When this size is `28` it seems that `mdat` size is incorrectly calculated using aforementioned parser.

I applied a patch to correctly calculate the `mdat` size though admittedly it feels like a bit of a hack rather than proper parsing.

Despite this "hack" the java ported mp4 parser now works correctly for the three existing mp4 files I already tested and the two files you submitted. It also processes all of them in the order of >1ms which is nice :)

Going to close this now as after updating to the latest version on npm (2.1.3 at time of writing) the issues should be resolved. Once again feel free to post comments if this is not the case after you've updated.

**Comment by SidOfc** [comment]
Figured out what it was after taking a dive in Apple QuickTime reference (https://developer.apple.com/library/archive/documentation/QuickTime/QTFF/QTFFChap1/qtff1.html)

Turns out it was not about `ftyp` header size, but rather when the `size` specified in the header for the current atom is `1` it indicates an _extended size_ field being present. This is then the actual size of the atom.

Since initial "patch" for this was more of a hack anyway I replaced it with a proper fix which should work in more scenarios.

Always a journey when trying to find and make sense of the specs 😂

**Comment by lehni** [comment]
Oh wow, that's great news! I'll give this a go tomorrow, thank you!

**Comment by lehni** [comment]
@SidOfc works like a charm, thank you! The only thing that is a bit weird is when working on partial data during multipart uploads, I get results back before they're actually valid, e.g.

`{ width: 0, height: 0, size: 32632, mime: 'video/mp4' }`

This is after the first multipart package of 32632 size is received. leather can determine the mime type, but not the dimensions because it's the file where the audio track appears to come first. 

I work around it like this:

```js
if (size.mime && (size.width > 0 || size.height > 0)) {
  done(size)
}
```

**Comment by lehni** [comment]
Oh and last feedback for now: I find `attributes` a bit strange and too generic as an import that one would use in the context of a broader project, because it does not indicate that it's a method reading something or returning something. It sounds like the name of a local variable. I therefore import  it like this:

```js
import { attributes as readMediaAttributes } from 'leather'
```

Something to think about...

**Comment by SidOfc** [comment]
@lehni the `attributes` functions work on provided data, there is no "future data" handling. I do not think this falls within scope of leather itself and should be handled by end-users instead.

As for the actual name, `attributes` was chosen in isolation. The name `readMediaAttributes` is quite clear indeed and I think I'll add such export in addition to deprecating `attributes` in the near future.

**Comment by lehni** [comment]
@SidOfc I agree with what you're saying. But I do think it's wrong to return `0` for `width` and `height` when they couldn't be read. It would be better if they were `null` or `undefined` in this case.

**Comment by SidOfc** [comment]
@lehni this is jumping to yet another topic. If you'd like to discuss this please open a new issue.

**Comment by lehni** [comment]
@SidOfc haha yeah sorry :) It's fine the way it is, I doubt any media file would be able to have dimension values of `0` so I guess that's equally valid to indicate `not read`. Thanks for all the great work on this and the swift responses and changes! It's very rare in OSS and much appreciated!

**Comment by SidOfc** [comment]
No problem at all, I do see your point that it could be ever so slightly cleaner though my reasoning was that since an object with valid `size` is always returned, it would make some sense to return `0` defaults for `width` and `height` as one could be doing calculations for them and they would have to handle `null` checks.

If there is solid reasoning for why `null` is better I would encourage opening a new issue, I am only human after all and **definitely** do not see everything correctly :)

**Comment by lehni** [comment]
It's great the way it is and one can reason for either approach to be more correct :)
